[theme]
theme = "space-villain"

[icons]
icons = "material-nf"

[[block]]
block = "custom"
# command = "echo 'Posture Check'"
command = "echo '{\"icon\":\"weather_thunder\",\"state\":\"Good\", \"text\": \"Posture Check\"}'"
json = true

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20,rot_interval:0.5)}"
format_alt = " $icon "
player = ["spotify", "vlc"]
separator = "-"

[[block]]
block = "bluetooth"
mac = "30:50:75:FA:CF:59"
format = " $icon $name "
disconnected_format = ""
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "net"
format = " ^icon_net_down$speed_down.eng(prefix:K) ^icon_net_up$speed_up.eng(prefix:K)"
format_alt = " $icon {$signal_strength $ssid}"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
device = "intel_backlight"
format = "$icon$brightness "

[[block]]
block = "battery"
format = "$icon$percentage"
interval=2
full_format="$icon 100%"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m/%y %R') "
